### ISSUE TITLE
Error on switching rollup example to rollup-plugin-vue2 

### ISSUE THREAD

**Issue by mario-minati** [jhthorsen/mojolicious-plugin-assetpack#139]
We tried to set up an example with Rollup Pipe based on the rollup.pl example. We just changed 'rollup-plugin-vue' to 'rollup-plugin-vue2'. This leads to the follwing error:

```
~/src/mojolicious-plugin-assetpack$ morbo examples/rollup.pl 
Server available at http://127.0.0.1:3000
[Sat Oct  6 14:22:07 2018] [warn] Installing rollup... Please wait. (npm install rollup)
npm WARN saveError ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN examples No description
npm WARN examples No repository field.
npm WARN examples No README data
npm WARN examples No license field.

+ rollup@0.66.4
added 3 packages from 34 contributors and audited 3 packages in 6.116s
found 0 vulnerabilities

[Sat Oct  6 14:22:14 2018] [warn] Installing vue-template-compiler... Please wait. (npm install vue-template-compiler)
npm WARN saveError ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN examples No description
npm WARN examples No repository field.
npm WARN examples No README data
npm WARN examples No license field.

+ vue-template-compiler@2.5.17
added 3 packages from 2 contributors and audited 8 packages in 3.107s
found 0 vulnerabilities

[Sat Oct  6 14:22:18 2018] [warn] Installing rollup-plugin-node-resolve... Please wait. (npm install rollup-plugin-node-resolve)
npm WARN saveError ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN examples No description
npm WARN examples No repository field.
npm WARN examples No README data
npm WARN examples No license field.

+ rollup-plugin-node-resolve@3.4.0
added 5 packages from 5 contributors and audited 15 packages in 4.424s
found 0 vulnerabilities

[Sat Oct  6 14:22:23 2018] [warn] Installing rollup-plugin-commonjs... Please wait. (npm install rollup-plugin-commonjs)
npm WARN saveError ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN examples No description
npm WARN examples No repository field.
npm WARN examples No README data
npm WARN examples No license field.

+ rollup-plugin-commonjs@9.1.8
added 43 packages from 33 contributors and audited 78 packages in 12.252s
found 0 vulnerabilities

[Sat Oct  6 14:22:36 2018] [warn] Installing rollup-plugin-vue2... Please wait. (npm install rollup-plugin-vue2)
npm WARN saveError ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/glue/src/mojolicious-plugin-assetpack/examples/package.json'
npm WARN examples No description
npm WARN examples No repository field.
npm WARN examples No README data
npm WARN examples No license field.

+ rollup-plugin-vue2@0.8.0
added 3 packages from 3 contributors and audited 352 packages in 4.063s
found 0 vulnerabilities

(node:20645) UnhandledPromiseRejectionWarning: Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/glue/src/mojolicious-plugin-assetpack/examples/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/glue/src/mojolicious-plugin-assetpack/examples/node_modules/rollup/dist/rollup.js:13361:9)
    at tryParse (/home/glue/src/mojolicious-plugin-assetpack/examples/node_modules/rollup/dist/rollup.js:13019:16)
    at Module.setSource (/home/glue/src/mojolicious-plugin-assetpack/examples/node_modules/rollup/dist/rollup.js:13092:33)
    at /home/glue/src/mojolicious-plugin-assetpack/examples/node_modules/rollup/dist/rollup.js:21761:20
(node:20645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20645) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?

**Comment by mario-minati** [comment]
If I can help coding a solution you can give me some hint what causes that error and I'll try to support your development. :-)

**Comment by mario-minati** [comment]
The usage of rollup-plugin-vue2 is kind of outdated as [github states](https://github.com/thgh/rollup-plugin-vue2). We don't follow that path any longer.
