### ISSUE TITLE
Repeated asset generation / hard to kill test server on errors in SCSS

### ISSUE THREAD

**Issue by zoffixznet** [jhthorsen/mojolicious-plugin-assetpack#45]
Not sure if this is because I'm telling `morbo` to watch the current directory, but it seems if there are parse errors in `.scss` files, the server keeps trying to generate them over and over again, and trying to kill `morbo` with `CTRL+C` is almost impossible.

Steps to reproduce:
```
git clone https://github.com/zoffixznet/SAMPLES-Mojo-Asset-Pack-Errors;
cd SAMPLES-Mojo-Asset-Pack-Errors/;
morbo -w . test.pl;
```
Now open `public/two.scss` and uncomment `color: $two-color;` line. `morbo` will now start spewing errors into log repeatedly, and pressing `CTRL+C` doesn't kill the server. *Note*: this issue doesn't happen if you introduce the error before starting the server or if it's introduced to `public/one.scss`. I think this might be related to #44 .

Here's the output in the log, when we trigger that infinite error/reloading. The interrupt lines (`linux/rbconfig.rb:163:in `expand': Interrupt`) is the output produced when trying to press `CTRL+C`

```
[Sun Mar 29 12:26:05 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:05 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
[Sun Mar 29 12:26:07 2015] [debug] Your secret passphrase needs to be changed
[Sun Mar 29 12:26:07 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=65, $!=25) Error: Undefined variable: "$two-color".
        on line 3 of standard input
  Use --trace for backtrace.

[Sun Mar 29 12:26:07 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:07 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
[Sun Mar 29 12:26:09 2015] [debug] Your secret passphrase needs to be changed
[Sun Mar 29 12:26:09 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=65, $!=25) Error: Undefined variable: "$two-color".
        on line 3 of standard input
  Use --trace for backtrace.

[Sun Mar 29 12:26:09 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:09 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
^C^C[Sun Mar 29 12:26:10 2015] [debug] Your secret passphrase needs to be changed
^C[Sun Mar 29 12:26:10 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=0, $!=4) /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:163:in `expand': Interrupt
	from /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:169:in `expand'
	from /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:163:in `gsub!'
	from /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:163:in `expand'
	from /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:180
	from /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:179:in `each_value'
	from /usr/lib/ruby/1.8/i686-linux/rbconfig.rb:179
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:29:in `require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:29
	from /usr/local/bin/sass:9:in `require'
	from /usr/local/bin/sass:9

[Sun Mar 29 12:26:10 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:10 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
^C[Sun Mar 29 12:26:10 2015] [debug] Your secret passphrase needs to be changed
^C[Sun Mar 29 12:26:10 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=0, $!=4) /usr/lib/ruby/1.8/pathname.rb:1083: Interrupt
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/sass-3.4.13/bin/../lib/sass/util.rb:9
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/sass-3.4.13/bin/../lib/sass/version.rb:2
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/sass-3.4.13/bin/../lib/sass.rb:4
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/sass-3.4.13/bin/sass:6
	from /usr/local/bin/sass:19:in `load'
	from /usr/local/bin/sass:19

[Sun Mar 29 12:26:10 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:10 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
^C^C[Sun Mar 29 12:26:10 2015] [debug] Your secret passphrase needs to be changed
[Sun Mar 29 12:26:11 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=65, $!=25) Error: Undefined variable: "$two-color".
        on line 3 of standard input
  Use --trace for backtrace.

[Sun Mar 29 12:26:11 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:11 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
[Sun Mar 29 12:26:12 2015] [debug] Your secret passphrase needs to be changed
[Sun Mar 29 12:26:13 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=65, $!=25) Error: Undefined variable: "$two-color".
        on line 3 of standard input
  Use --trace for backtrace.

[Sun Mar 29 12:26:13 2015] [info] Built asset for app.css: /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public/packed/app-4571436571090e6ec26a9bd646c9b15b.err.css
[Sun Mar 29 12:26:13 2015] [debug] Using fallback asset for app.css: app-1e177f24229faceddc82e8046cd6922d.min.css
[Sun Mar 29 12:26:14 2015] [debug] Your secret passphrase needs to be changed
[Sun Mar 29 12:26:15 2015] [error] Failed to run '/usr/local/bin/sass --stdin --scss -I /tmp/z3/SAMPLES-Mojo-Asset-Pack-Errors/public -t compressed' ($?=65, $!=25) Error: Undefined variable: "$two-color".
        on line 3 of standard input
  Use --trace for backtrace.
```

**Comment by jhthorsen** [comment]
Watching "." is not supported. No idea how to make that work.
